[firebase]
type = "service_account"
project_id = "ecocart-7e989"
private_key_id = "d0f02928f535b0d756706c9184d4bdba2bc696b7"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvwIBADANBgkqhkiG9w0BAQEFAASCBKkwggSlAgEAAoIBAQCufJ7BcGFLa3y8
8FKRGPw1ht/VRkf7k8Jf6yaW3WJChSEq2ObEYHuzImJo9nSGPjCX/jQfIxTy6lcH
5bavfu1lVGhbfkCRGCprQITtteSrQ3vOA4CVnoENzQZzfjZsRMaUw51m/OxPoCJ+
b2x4oQyp9LWoI8x6m8OLPXMS8+oDBJ+spRkGWCtRyCtly+zivo5TGysvAPOKT3UK
KJbuWk3COs+zHwEzUlqvRpicaXUXaY+vbL4yw7LXw2FvvQHKX6tJoAncSdwyPChW
SxIWTmZ3IvBGVwphh/+0i2kgTFBw/aCdXeWXwyCtYRWHLv6mLFT8F/FoORoq+VsZ
xc62flYrAgMBAAECggEAITZaV5KnCl6O0z3hUXoSg7PFBkkG6ZWSAYT2hu/jxKqn
igrYPhfpY8sPNVB4FJdg04WQ8T5Rvf0qDLhGYjhEQq3i4UtyScvyQxD4XHDrckf5
mFilUJVnljNo33HuNQSQUf+8Bb7t0ig2eJ+H45wwF2ebbkJGKS5d9bKAJWLlL6aP
9IwkHsH5opZyayfjLnoDrjPa7zU8jTE7ba7an4I/h/+eb7juZf9eKHzEWFYr6gkl
TbbJGA072Ee4lJdY2Lo0VkXzV4EssyiLj2XwotPT6RvcwZbdZ1+P4HvOG0CZ0ujc
i202D/mo9FYhvR2bfQTOaIq01G8n90h4CFC+IYybzQKBgQDyFG9cYM2lg3KJTdJv
3q9eXRrno3SCjCnI5q0m1OIMJySm29JSPfBQkyI6ae1rRUg9ZCF7UMwBg1tzzIar
lC4XbBMj4c1EPWhohGwjjLhxRilRbp2hJEFZUbqJsNrAj5HNQeGDiJN1CASSwKu0
8fFamDfCIIflOr9iL3e7VRV6RQKBgQC4hSyE5qzwptvoWSANYTQ8gW+kuaB/BVrS
Uj7nAYicgzoQWfcIb3EJq/NYO8U0NFi5OXLKUfA5kFa2mgz8ijWJeLh2wtoBQemZ
wL7N2dO2pFfpNGNk0oBc0G4BwciIOcY3ETOkvcV7Rqa0wvnZ0PR3aZa1cvkeEWlh
sa30d/VNrwKBgQCkyn5oT0mOo2WjzEM1fky5Gv5Gs0GL4OhM56L1bTOX/El6AOgy
rhFaeF5zj0pcnKQpjnEwZfcKDKaDtLX0NQIPVbXN1leKXZcmlwaaSKACFDXqRjet
y2Vk7Trjom23acRiCrf+d0mSAGxEjj4VBiI7fqVuVADObeh8aT3DW48sVQKBgQCT
JPAZk3J5/jYDlX8v7EIhtf531+ebI4QHkLrEsL5mQWd+Pp/2xBfaZJsL064xMUVH
f/6ARNNStD3SJAsTIIwM8o33du8ubYeBquj9cyWX0nqgZ7yTXCIs4bG4CPaHW7sr
krYiO4tOAUtTfuCLyEwLJdKfI+5xAeWNmIlmGHsv1QKBgQCEdMSwCp9Pqn+hWR1K
JcSUnheWHDsYDUT0Sm+m05kEar5yjp+za9/1jh9WngxdwMJFR9U7GS5KHHn42+G6
fgDHL7eINLebqXI8ouCrkQuQpV0cWHwpk+KVKdrK94ZavehcDk4K0GDttaslZ32D
AD56h+178z2F/43C8bNmeWlYEg==
-----END PRIVATE KEY-----"""
client_email = "firebase-adminsdk-fbsvc@ecocart-7e989.iam.gserviceaccount.com"
client_id = "108726516924283979518"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk-fbsvc@ecocart-7e989.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
